spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://localhost:5432/marketdb?sslmode=disable}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASS:postgres}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    # XML master dosyanı işaret ediyoruz (YAML/JSON değil!)
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: ${PORT:8080}

# (Opsiyonel) Actuator health için:
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

# (Opsiyonel) Log ayarı – Liquibase ilerlemesini görmek istersen:
logging:
  level:
    liquibase: info
